// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA395o5VbcJ2NgUJP_s907lP64AxUhfrVk',
    appId: '1:1049650884656:web:e82ad2ee1f45fd53e97df5',
    messagingSenderId: '1049650884656',
    projectId: 'my-ai-notes-d1636',
    authDomain: 'my-ai-notes-d1636.firebaseapp.com',
    storageBucket: 'my-ai-notes-d1636.appspot.com',
    measurementId: 'G-2G08WYZ49C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG1Z-suIQc6rxI4wl4x55BCsb-Pb-gBIg',
    appId: '1:1049650884656:android:3568e0e260f04b4ee97df5',
    messagingSenderId: '1049650884656',
    projectId: 'my-ai-notes-d1636',
    storageBucket: 'my-ai-notes-d1636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdXm4sMGrSL7zmPhs5_0H9Mj4-Nv96-ww',
    appId: '1:1049650884656:ios:32d32950ba9dfb93e97df5',
    messagingSenderId: '1049650884656',
    projectId: 'my-ai-notes-d1636',
    storageBucket: 'my-ai-notes-d1636.appspot.com',
    iosClientId: '1049650884656-gav4itnpuggpdhl5si5iah6gpuft81ql.apps.googleusercontent.com',
    iosBundleId: 'ng.ikemesit.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdXm4sMGrSL7zmPhs5_0H9Mj4-Nv96-ww',
    appId: '1:1049650884656:ios:32d32950ba9dfb93e97df5',
    messagingSenderId: '1049650884656',
    projectId: 'my-ai-notes-d1636',
    storageBucket: 'my-ai-notes-d1636.appspot.com',
    iosClientId: '1049650884656-gav4itnpuggpdhl5si5iah6gpuft81ql.apps.googleusercontent.com',
    iosBundleId: 'ng.ikemesit.notes',
  );
}
